version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/tomato
    depends_on:
      - mongo
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://backend:5000
    ports:
      - "3000:3000"

  admin:
    build:
      context: ./admin
      args:
        VITE_API_URL: http://backend:5000
    ports:
      - "3001:3000"  # Note: internal port is 3000, external is 3001

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
